version: v1

labels:
  - label: "enhancement"
    matcher:
      title: "^feat(\\(.+\\))?!?:.*"
  - label: "bug"
    matcher:
      title: "^fix(\\(.+\\))?!?:.*"
  - label: "documentation"
    matcher:
      title: "^docs(\\(.+\\))?!?:.*"
  - label: "performance"
    matcher:
      title: "^perf(\\(.+\\))?!?:.*"
  - label: "refactor"
    matcher:
      title: "^refactor(\\(.+\\))?!?:.*"
  - label: "test"
    matcher:
      title: "^test(\\(.+\\))?!?:.*"
  - label: "ci"
    matcher:
      title: "^ci(\\(.+\\))?!?:.*"
  - label: "build"
    matcher:
      title: "^build(\\(.+\\))?!?:.*"
  - label: "dependencies"
    matcher:
      title: "^(chore\\(deps\\)|deps)(\\(.+\\))?!?:.*"
  - label: "chore"
    matcher:
      title: "^chore(?!\\(deps\\))(\\(.+\\))?!?:.*"
  - label: "i18n"
    matcher:
      title: "(?i).*(i18n|locale|translation|translate).*"
  - label: "breaking-change"
    matcher:
      title: "^[a-z]+(\\(.+\\))?!:.*"
