version: 1

labels:
  - label: "enhancement"
    matcher:
      title: "^feat(\\(.+\\))?!?:.*"
  - label: "bug"
    matcher:
      title: "^fix(\\(.+\\))?!?:.*"
  - label: "documentation"
    matcher:
      title: "^docs(\\(.+\\))?!?:.*"
  - label: "type:performance"
    matcher:
      title: "^perf(\\(.+\\))?!?:.*"
  - label: "type:refactor"
    matcher:
      title: "^refactor(\\(.+\\))?!?:.*"
  - label: "type:test"
    matcher:
      title: "^test(\\(.+\\))?!?:.*"
  - label: "type:ci"
    matcher:
      title: "^ci(\\(.+\\))?!?:.*"
  - label: "type:build"
    matcher:
      title: "^build(\\(.+\\))?!?:.*"
  - label: "dependencies"
    matcher:
      title: "^(chore\\(deps\\)|deps)(\\(.+\\))?!?:.*"
  - label: "type:chore"
    matcher:
      title: "^chore(?!\\(deps\\))(\\(.+\\))?!?:.*"
  - label: "type:i18n"
    matcher:
      title: "(?i).*(i18n|locale|translation|translate).*"
  - label: "type:breaking"
    matcher:
      title: "^[a-z]+(\\(.+\\))?!:.*"
